<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframelightbox-iframe-ab300529-3f9f-48ad-91_03491e</name>
   <tag></tag>
   <elementGuidId>88d5fa1d-7edc-49ab-b944-7baca215b7fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lightbox-iframe-ab300529-3f9f-48ad-9192-5eae104a5114</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='lightbox-iframe-ab300529-3f9f-48ad-9192-5eae104a5114']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>20ab29bf-2dff-48c9-823e-2a50510d41f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>21557f9c-59ae-4067-aaa0-8c0bf2e8bec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Modal Overlay Box Frame</value>
      <webElementGuid>2e50c425-50a7-40fb-a97c-dd12b670f9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lightbox-iframe-ab300529-3f9f-48ad-9192-5eae104a5114</value>
      <webElementGuid>a3f2ed80-5dab-425e-825a-48de0f45e5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sidebar 1: Career Center 2.0 Launch </value>
      <webElementGuid>2e620b92-0bed-4c8c-a2d8-30db454bc421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-263192</value>
      <webElementGuid>d608c2b2-f044-499f-a02c-4e21b12e3af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8a67afa2-af7b-4ff7-af88-2e138968bbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d04a151a-a4a5-46ca-b58f-3c72173c578e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a89d8db-3f3a-41b7-a0bc-e02c209424d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e5fac19b-83a4-4b91-8115-021b51d04574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts allow-same-origin allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-top-navigation</value>
      <webElementGuid>0e8210e7-d0bd-45bd-a9fb-5359a0c570f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lightbox-iframe-ab300529-3f9f-48ad-9192-5eae104a5114&quot;)</value>
      <webElementGuid>867bd3a8-ea37-4052-a3e2-ec9b442dc2a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='lightbox-iframe-ab300529-3f9f-48ad-9192-5eae104a5114']</value>
      <webElementGuid>2f74d9e3-6e85-4556-9121-20a4409a6805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox-ab300529-3f9f-48ad-9192-5eae104a5114-1699909088460']/iframe</value>
      <webElementGuid>2770fb19-d643-4611-9adf-d497fd500577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/iframe</value>
      <webElementGuid>a7c8e969-f608-4f93-8644-2cdd4619ccc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'lightbox-iframe-ab300529-3f9f-48ad-9192-5eae104a5114' and @title = 'Sidebar 1: Career Center 2.0 Launch ']</value>
      <webElementGuid>c1648653-4835-4bc6-9b50-b8a4fe966d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
