<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputfilter-exercises-input</name>
   <tag></tag>
   <elementGuidId>d8081ffc-1a1c-4664-9d1c-4ef7575df96a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-exercises-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter-exercises-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40ac987c-37b1-415d-9b63-18b41186c668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-exercises-input</value>
      <webElementGuid>a9f9879f-ff98-430a-84a1-98ed79928e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_exercises')</value>
      <webElementGuid>569e51ac-4d86-4fb9-acd5-f0a3963c881e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc5369a9-fd60-4330-bc00-db2a0143eb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>7b77dbd5-199a-4520-b400-2bd3e66cc406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>a118e42e-5852-461f-b18d-f5b55f81f16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exercises filter bar</value>
      <webElementGuid>d3c46674-a405-429f-b359-630cec75d636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-exercises-input&quot;)</value>
      <webElementGuid>ebb5e159-ff7d-408a-a817-8c8e76551e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-exercises-input']</value>
      <webElementGuid>783a081e-0b34-4aed-b322-b095c5e74dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exercises_list']/div/div[2]/div/input</value>
      <webElementGuid>bb9f37e3-8d71-45a5-9856-5806369f0331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>e73263ae-7249-430a-bf3d-54b67bf7734a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-exercises-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>7da50435-6aec-4315-bb27-77fd94506557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
