<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputfilter-certified-input</name>
   <tag></tag>
   <elementGuidId>5102a23c-0416-4df3-84a5-cd34af9da703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-certified-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter-certified-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d40659f1-e726-4f7e-a462-b91ff314d9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-certified-input</value>
      <webElementGuid>d665fdd5-c039-43ea-8567-1790174c125e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_certified')</value>
      <webElementGuid>03f8641d-07de-4ef4-a125-cd5c6e059aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>829b01cc-5763-41ad-97ea-647bd235a87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>44b408e9-a392-4779-924c-ca0214e89146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>4e9445fd-3235-4b80-bc9c-79180501ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Certificate filter bar</value>
      <webElementGuid>c3f6f64d-e47b-42d0-8043-6cc0ff32c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-certified-input&quot;)</value>
      <webElementGuid>f3136a07-3daf-4833-8a83-83d9f82460e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-certified-input']</value>
      <webElementGuid>fba9eed9-074e-47c5-a661-dba94e04dbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='certified_list']/div/div[2]/div/input</value>
      <webElementGuid>86ee3e6d-847c-4dca-9a1f-b040e6289c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>2b61ded7-403a-4b74-99a9-ea818d5af3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-certified-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>ff4813ba-c78f-4d58-85bb-207c5c77e121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
