<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tutorial</name>
   <tag></tag>
   <elementGuidId>8f0ba008-b56c-48a0-9c58-b6e835f9a22b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.color_h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1f81405-77d7-4351-84f1-52e466cc76ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>color_h1</value>
      <webElementGuid>64f83967-d380-4379-b683-87b4a5ad01ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tutorial</value>
      <webElementGuid>d50bd1ed-39c9-4209-807b-9e435e2d303a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/h1[1]/span[@class=&quot;color_h1&quot;]</value>
      <webElementGuid>83f8ead6-8c2c-4123-9eb7-dfe2d6c703c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/h1/span</value>
      <webElementGuid>a0ebba69-d3d0-4556-9945-00ba9e665760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>e8b4cc45-cad4-4ef1-9160-8e407935e424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tutorial' or . = 'Tutorial')]</value>
      <webElementGuid>c3a56a3d-1f03-4e9e-b0cd-115d80b7c365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
