<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign In to Account</name>
   <tag></tag>
   <elementGuidId>3f9bb77c-a4e9-4d59-8136-bdf5c9d03a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-menu']/ul/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.AnchorLink.LoginMenu__item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d08272a4-25f8-4250-a7f0-a5433c800742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AnchorLink LoginMenu__item</value>
      <webElementGuid>3536b976-a6bb-45dc-83ce-d9955da4c204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0437940e-cca0-44af-adbc-b8adad55604e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f7e49759-1cd1-43f7-a1c7-ddfe2204b112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-global.tagid</name>
      <type>Main</type>
      <value>f_oneid06</value>
      <webElementGuid>80f8d408-a960-4c4e-801d-5aef3c750321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-link_type</name>
      <type>Main</type>
      <value>lnk_o</value>
      <webElementGuid>2dbb9d3f-c61f-4ffa-9ca1-454fec2b2acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-link_name_custom</name>
      <type>Main</type>
      <value>abc:Home - Free View:oneid sign in initiation</value>
      <webElementGuid>d860c5e9-05c2-45e6-95f2-f2ef6da9fb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In to Account</value>
      <webElementGuid>1a19f947-2580-4196-a1bd-98f55cd4747d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-menu&quot;)/ul[@class=&quot;LoginMenu__wrapper&quot;]/a[@class=&quot;AnchorLink LoginMenu__item&quot;]</value>
      <webElementGuid>882332cb-325f-42f6-bba1-2edcd3816c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-menu']/ul/a</value>
      <webElementGuid>5128ad36-a3d0-48b0-8214-0e7068004e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign In to Account')]</value>
      <webElementGuid>2324495b-910b-4ec6-97fd-f0b519bed209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>f516deca-ce57-4746-b5d0-e77d69af6606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/a</value>
      <webElementGuid>ebdc16a9-08f9-4110-b609-0b8f20c96007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Sign In to Account' or . = 'Sign In to Account')]</value>
      <webElementGuid>f4e8e738-5482-448d-8ab2-dd619038fd0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
