<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_try</name>
   <tag></tag>
   <elementGuidId>fe0d221b-cf51-46cd-8c4c-296e8d92febb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fitt-analytics']/div/main/nav/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.AnchorLink.ext__button.fitt-tracker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a46fc679-6850-4409-bc71-297c9a7e4c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AnchorLink ext__button fitt-tracker</value>
      <webElementGuid>989f2958-f3ed-4d22-895a-495fef68b383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22fbbd58-ae66-48cb-9f19-32bc8aaf45f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>try hulu</value>
      <webElementGuid>72bdf584-62f4-46b4-bce5-1f2b52af99ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-global.tagid</name>
      <type>Main</type>
      <value>f_click01</value>
      <webElementGuid>f00fe60b-fdd2-40ef-86f7-a24fce929774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-cta_text</name>
      <type>Main</type>
      <value>hulu</value>
      <webElementGuid>6bb84133-a4b0-4e31-8e12-e71f1b1ad890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-link_name_custom</name>
      <type>Main</type>
      <value>abc:homepage:main_menu:hulu</value>
      <webElementGuid>b116dd0e-9559-43bf-b85f-18d339747291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-position_number</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>71855db1-29ec-4a21-82bb-7beec0f09eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-module_position_number</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1b5268c4-6820-4bdf-b566-d647cf0997e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-content_language</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>65c31c32-c2d6-450c-8d29-5a29df9d35e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-section_page</name>
      <type>Main</type>
      <value>main_menu</value>
      <webElementGuid>261d150c-fced-4e64-ad81-18bc3e6bf7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-collection_name</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>45c2ec88-48f1-48b8-b7fa-6dead653d7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f173d59b-bee1-480c-9210-f1c34688b9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.hulu.com/welcome?cmp=17728&amp;utm_campaign=OO_ABC_NavButton_OnChannel_Hulu&amp;utm_medium=Display&amp;utm_source=OO_ABC</value>
      <webElementGuid>97cc1e10-84ac-4a5e-bfe7-19eb3365ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>try</value>
      <webElementGuid>d3dbdb52-257a-4cb3-a14a-1c777db94500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;navigation__container&quot;]/div[@class=&quot;navigation__menu&quot;]/a[@class=&quot;AnchorLink ext__button fitt-tracker&quot;]</value>
      <webElementGuid>1250b55b-a44b-4e9f-97da-f9cc39017289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fitt-analytics']/div/main/nav/div/div/a</value>
      <webElementGuid>672de1d5-e5e7-4b00-bf6e-5a6d2810ce39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.hulu.com/welcome?cmp=17728&amp;utm_campaign=OO_ABC_NavButton_OnChannel_Hulu&amp;utm_medium=Display&amp;utm_source=OO_ABC')]</value>
      <webElementGuid>429af96c-067b-4ef1-9c75-112b8fcef593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/a</value>
      <webElementGuid>e09971d3-0f08-47bf-8cc9-73c57b5fcce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.hulu.com/welcome?cmp=17728&amp;utm_campaign=OO_ABC_NavButton_OnChannel_Hulu&amp;utm_medium=Display&amp;utm_source=OO_ABC' and (text() = 'try' or . = 'try')]</value>
      <webElementGuid>6804bb64-0a7a-433a-92dc-af55b192e6cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
