<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook</name>
   <tag></tag>
   <elementGuidId>2db02888-e98c-49a0-b309-524d11a88795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fitt-analytics']/div/main/footer/section/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>201bf548-5c64-4d4d-9666-b870503d41df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-section_page</name>
      <type>Main</type>
      <value>footermenu</value>
      <webElementGuid>55eee095-8e41-413b-994e-7893648d064f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fitt-tracker</value>
      <webElementGuid>585edd7c-7a87-4a5d-a089-512c6bbcaac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>caad1c79-8cdf-4164-9250-caabae3a02d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/footer[@class=&quot;footer grouped gap&quot;]/section[@class=&quot;footer__wrapper footer__menu flex&quot;]/div[@class=&quot;footer__group&quot;]/div[@class=&quot;fitt-tracker&quot;]</value>
      <webElementGuid>4e5b5902-2c83-4e44-8387-7ab103053652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fitt-analytics']/div/main/footer/section/div[3]/div[2]</value>
      <webElementGuid>34e043c0-e5f0-403c-93da-eee06907c3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>14ef8490-dcfe-4fe5-9202-04be8fbde0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Facebook' or . = 'Facebook')]</value>
      <webElementGuid>0934c745-c417-4010-a2c0-28941a557790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
