<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_browse</name>
   <tag></tag>
   <elementGuidId>a3c4a7a7-4062-4328-a008-04bc59170c95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='browse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#browse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a3b551e-118a-4c4a-9693-f8f603734514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navButton</value>
      <webElementGuid>435bd53a-bca1-4403-b368-a81143e2f26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>97356a60-4112-4fce-b317-8a05ce6512fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>7b49a0cb-5143-4b83-a2fd-43a7a2bae64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;navigation__container&quot;]/div[@class=&quot;navigation__menu&quot;]/div[@class=&quot;navigation__group&quot;]/div[@id=&quot;browse&quot;]</value>
      <webElementGuid>2618fd04-3e6b-47d3-af3f-4b3be62fd459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='browse']</value>
      <webElementGuid>03c856c4-36ca-430f-8612-86a8cfb5cc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fitt-analytics']/div/main/nav/div/div/div/div[2]</value>
      <webElementGuid>31f90c2c-5cbf-480a-be0b-a12ccdd4f964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/div[2]</value>
      <webElementGuid>142d330d-26f9-4ded-9759-e87cec0d2096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'browse' and (text() = 'browse' or . = 'browse')]</value>
      <webElementGuid>db03d2b3-516f-4b87-9c10-94fcdbdfe8d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
