<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login__img__icon</name>
   <tag></tag>
   <elementGuidId>d130303e-22d2-4e09-9fd0-067f2f0113e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fitt-analytics']/div/main/nav/div/div/div[4]/div/div/button/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Login__img__icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d8995ba-2123-46cd-97af-8e099cf196c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-cdn.watchdisneyfe.com/delta/assets/common/account.png</value>
      <webElementGuid>9353b2db-422f-4d44-a679-48ee916e243b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Login__img__icon</value>
      <webElementGuid>0a91f859-a081-4bbc-86db-4878eebf584d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>account icon</value>
      <webElementGuid>f3d60a30-6c7d-4084-b0d6-173d39b3fb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;navigation__container&quot;]/div[@class=&quot;navigation__menu&quot;]/div[@class=&quot;Login&quot;]/div[@class=&quot;Login__wrapper&quot;]/div[@class=&quot;Login__content&quot;]/button[@class=&quot;Login__button&quot;]/span[@class=&quot;Login__button__icon&quot;]/img[@class=&quot;Login__img__icon&quot;]</value>
      <webElementGuid>843d0db3-9514-4536-a06c-42e91ebe8361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fitt-analytics']/div/main/nav/div/div/div[4]/div/div/button/span/img</value>
      <webElementGuid>051667b1-cd74-46d0-85f9-46609a170b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='account icon']</value>
      <webElementGuid>ce136d46-1498-4b96-8394-a36fdb48ff4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span/img</value>
      <webElementGuid>45c0d4e5-0ab8-4a37-aa41-38b6e6953120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets-cdn.watchdisneyfe.com/delta/assets/common/account.png' and @alt = 'account icon']</value>
      <webElementGuid>bd0c74fc-0a4c-4ece-8653-210e907039a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
