<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ext__logo</name>
   <tag></tag>
   <elementGuidId>3ce95fa4-e166-4950-be4a-728cf50ecbc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ext__logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e8a505a5-7765-4bc4-a9ae-4d91b81b5963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ext__logo</value>
      <webElementGuid>feb28850-6982-4523-b6ab-8d2c1bf3fdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-cdn.watchdisneyfe.com/delta/assets/common/ENT_heroLogo_Hulu@2x.png</value>
      <webElementGuid>f9b734c5-9173-4adc-970f-d46e6c5e8abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;navigation__container&quot;]/div[@class=&quot;navigation__menu&quot;]/a[@class=&quot;AnchorLink ext__button fitt-tracker&quot;]/img[@class=&quot;ext__logo&quot;]</value>
      <webElementGuid>9540efe8-e764-4e49-aa23-9154ac2758ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fitt-analytics']/div/main/nav/div/div/a/img</value>
      <webElementGuid>4cb5453c-58dd-4cf4-ac1e-5b8205750309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets-cdn.watchdisneyfe.com/delta/assets/common/ENT_heroLogo_Hulu@2x.png')]</value>
      <webElementGuid>3f4f2771-8dd4-4f3a-aeac-fc83e24ab59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>d11b6255-8b70-42e1-a57d-61ec24fd24b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets-cdn.watchdisneyfe.com/delta/assets/common/ENT_heroLogo_Hulu@2x.png']</value>
      <webElementGuid>c3b71e30-0ec4-4976-a7da-3a71bda530e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
