<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login__button__text</name>
   <tag></tag>
   <elementGuidId>4e716e3c-d6e4-4a86-9ad0-5475496632b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fitt-analytics']/div/main/nav/div/div/div[4]/div/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.Login__button__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>839e2818-0577-428f-b6a3-0afe96da5515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Login__button__text</value>
      <webElementGuid>f2fefa9c-658b-49d0-b53f-a77820296816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;navigation__container&quot;]/div[@class=&quot;navigation__menu&quot;]/div[@class=&quot;Login&quot;]/div[@class=&quot;Login__wrapper&quot;]/div[@class=&quot;Login__content&quot;]/button[@class=&quot;Login__button&quot;]/span[@class=&quot;Login__button__text&quot;]</value>
      <webElementGuid>d0b00676-87a0-40ee-92ea-a2c363dc043d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fitt-analytics']/div/main/nav/div/div/div[4]/div/div/button/span[2]</value>
      <webElementGuid>23a7941e-1e40-4997-9af9-f29da4021220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>eefa02b2-0175-45f1-b9a7-b1df67b63e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
