<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_schedule</name>
   <tag></tag>
   <elementGuidId>97cb0de1-27e5-481e-bd04-19650252a804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='schedule']/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule > a.AnchorLink.navButton__link.dib.hide-mobile.tc.fitt-tracker > div.abc__link > span.navButton__text.ttc.tc.dib</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>419c6a13-bcc3-4a60-ad0a-93ce1ce6bef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navButton__text ttc tc dib</value>
      <webElementGuid>6dcfe64f-34bf-44fc-b6d3-10e42927ad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>schedule</value>
      <webElementGuid>7e7ace07-b1f1-4be1-81b0-f71fa7081032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fitt-analytics&quot;)/div[@class=&quot;bp-mobileTablet bp-tablet bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus no-touch&quot;]/main[@class=&quot;layout page-home abc-com truncate-str-patch&quot;]/nav[@class=&quot;navigation&quot;]/div[@class=&quot;navigation__container&quot;]/div[@class=&quot;navigation__menu&quot;]/div[@class=&quot;navigation__group&quot;]/div[@id=&quot;schedule&quot;]/a[@class=&quot;AnchorLink navButton__link dib hide-mobile tc fitt-tracker&quot;]/div[@class=&quot;abc__link&quot;]/span[@class=&quot;navButton__text ttc tc dib&quot;]</value>
      <webElementGuid>221a4ce4-6c6f-4fdd-abda-f0eb6366e351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='schedule']/a/div/span</value>
      <webElementGuid>be953d70-6674-4c62-a382-4ffc7ab6474a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/span</value>
      <webElementGuid>a8b5487c-e891-4c05-a2fa-4c3d197f8f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'schedule' or . = 'schedule')]</value>
      <webElementGuid>e65ba7ed-7ae9-4684-8c22-20ca9db3447b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
