<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>5c72b1f8-e585-4f9c-a468-0db409df0a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d896c76-52d4-4060-be2c-d8154d9e5730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://codecademy.com/resources/blog?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.</value>
      <webElementGuid>a489fdbf-d98a-48fa-aadb-486e297fc807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>69fbc549-d5d3-42ed-8e39-fd3c72c0910b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gamut-gi2olp-AnchorBase e14vpv2g0</value>
      <webElementGuid>390649c5-07ac-4327-ae4e-aacf8533cc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>28b5a4a8-3204-4283-9cec-18a69ef0c22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;e8ekv6f0 gamut-1lly2r1-VariableProvider-AppWrapper-AppWrapper e1skjn880&quot;]/footer[@class=&quot;gamut-1y7hb43 e1xir4o10&quot;]/div[@class=&quot;gamut-3a1jmv-Box-ContentContainer e1dgn4f70&quot;]/div[@class=&quot;gamut-pnw1bs-LayoutGrid e1f7ortw0&quot;]/div[@class=&quot;gamut-1gkks2k-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-15b6f3e-LayoutGrid e10xj1580&quot;]/div[@class=&quot;gamut-6jvxk2-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-5kj303-Box ebnwbv90&quot;]/ul[@class=&quot;gamut-1jk5e01-Box ebdzcwh1&quot;]/li[@class=&quot;gamut-77pqup ebdzcwh0&quot;]/a[@class=&quot;gamut-gi2olp-AnchorBase e14vpv2g0&quot;]</value>
      <webElementGuid>a8053ab2-572c-48a2-82ab-dcbbc0c836d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>2d503916-097d-4ce1-96bc-5fe0aac808cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Blog')])[2]</value>
      <webElementGuid>de3e871d-655c-4f8a-a5b4-1291320b6d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://codecademy.com/resources/blog?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.')]</value>
      <webElementGuid>f87fa214-9028-45eb-ab9b-64597b302654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>d3f72757-1d7f-4860-9025-7dfd2df9a758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://codecademy.com/resources/blog?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>19d7a71a-bcb0-4199-92b2-5582bab18677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
