<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Code Crew</name>
   <tag></tag>
   <elementGuidId>ec298524-e35f-4a43-8be9-52be2545f9e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div/div/div[3]/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1db34b0b-5054-43d3-a239-7d4354692fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://try.codecademy.com/code-crew/?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.</value>
      <webElementGuid>840fb581-d1da-4476-8f78-4f4475ffcd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>829d5a46-1a32-4d4d-b17d-92c9f08ba6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gamut-gi2olp-AnchorBase e14vpv2g0</value>
      <webElementGuid>15f2045c-5bc9-4173-bd8e-97f97d91707a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Code Crew</value>
      <webElementGuid>156290d2-9a81-47f1-8566-53f31c968a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;e8ekv6f0 gamut-1lly2r1-VariableProvider-AppWrapper-AppWrapper e1skjn880&quot;]/footer[@class=&quot;gamut-1y7hb43 e1xir4o10&quot;]/div[@class=&quot;gamut-3a1jmv-Box-ContentContainer e1dgn4f70&quot;]/div[@class=&quot;gamut-pnw1bs-LayoutGrid e1f7ortw0&quot;]/div[@class=&quot;gamut-1gkks2k-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-15b6f3e-LayoutGrid e10xj1580&quot;]/div[@class=&quot;gamut-1oivdx9-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-1efsrtw-Box ebnwbv90&quot;]/ul[@class=&quot;gamut-1jk5e01-Box ebdzcwh1&quot;]/li[@class=&quot;gamut-77pqup ebdzcwh0&quot;]/a[@class=&quot;gamut-gi2olp-AnchorBase e14vpv2g0&quot;]</value>
      <webElementGuid>952b14ca-cc83-4951-b7fb-54ba6dae9206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div/div/div[3]/div[2]/ul/li[2]/a</value>
      <webElementGuid>ae3c695a-32bb-4e8e-b147-8470b66cb911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Code Crew')])[2]</value>
      <webElementGuid>8a8dc6d6-e9f2-459d-9739-e82972dea21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://try.codecademy.com/code-crew/?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.')]</value>
      <webElementGuid>a5c222b6-dd33-454f-9bc2-ee81515296d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/ul/li[2]/a</value>
      <webElementGuid>bfc8b4f3-5566-4d75-96a6-51ac02d8173a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://try.codecademy.com/code-crew/?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.' and (text() = 'Code Crew' or . = 'Code Crew')]</value>
      <webElementGuid>d3989d53-963a-4001-add6-2f8ecdfe3536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
