<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_e1am55213 gamut-mwvz2s-AnchorBase e14vpv2g0</name>
   <tag></tag>
   <elementGuidId>8bcc9c75-11fe-492d-b7db-2236318069e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.e1am55213.gamut-mwvz2s-AnchorBase.e14vpv2g0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div[2]/div/div/div[3]/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a3b3cdc-957f-42b0-a477-8ed8763a9a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://itunes.apple.com/us/app/codecademy-go/id1376029326</value>
      <webElementGuid>6f071cf6-6513-4a95-9ac0-137c9fc4629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d7c914b7-a43b-49ee-b60a-371fb1142e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>d5c41a49-98a3-432e-a3db-c10b87060c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e1am55213 gamut-mwvz2s-AnchorBase e14vpv2g0</value>
      <webElementGuid>59c265ab-dea0-4c98-b098-5ee85a9fcd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;e8ekv6f0 gamut-1lly2r1-VariableProvider-AppWrapper-AppWrapper e1skjn880&quot;]/footer[@class=&quot;gamut-1y7hb43 e1xir4o10&quot;]/div[@class=&quot;gamut-3a1jmv-Box-ContentContainer e1dgn4f70&quot;]/div[@class=&quot;gamut-pnw1bs-LayoutGrid e1f7ortw0&quot;]/div[@class=&quot;gamut-1gkks2k-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-2ry0sg e1am55212&quot;]/div[@class=&quot;gamut-glpvwy-LayoutGrid e10xj1580&quot;]/div[@class=&quot;gamut-d1cdmh-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-5kj303-Box ebnwbv90&quot;]/ul[@class=&quot;gamut-1iy6mcl-Box ebdzcwh1&quot;]/li[@class=&quot;gamut-1ewuzsp-Box e1am55214&quot;]/a[@class=&quot;e1am55213 gamut-mwvz2s-AnchorBase e14vpv2g0&quot;]</value>
      <webElementGuid>194198f2-4d85-41e9-92ce-453bd74fd395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div[2]/div/div/div[3]/div[2]/ul/li/a</value>
      <webElementGuid>35a214a9-6908-4f00-a26a-c5190491e24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://itunes.apple.com/us/app/codecademy-go/id1376029326')]</value>
      <webElementGuid>9b76d48c-75fa-469b-8339-1a67d0883789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[2]/ul/li/a</value>
      <webElementGuid>5ed95ab3-f9cb-41d2-9a15-fb6a45efe412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://itunes.apple.com/us/app/codecademy-go/id1376029326']</value>
      <webElementGuid>7901f270-69fd-44e1-a276-446c3403e234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
