<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forums</name>
   <tag></tag>
   <elementGuidId>657fb6fb-6c6f-48ad-bbb9-de0fc04680e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div/div/div[3]/div[2]/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83771f59-b81e-4859-afe5-aa106560a12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://discuss.codecademy.com/?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.</value>
      <webElementGuid>c3595558-a0d8-4989-9edd-d2265ef6a0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>84ebc305-1a57-4ead-b223-38c785275f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gamut-gi2olp-AnchorBase e14vpv2g0</value>
      <webElementGuid>f88baf1b-9b8c-4212-8dd0-05bee62432af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forums</value>
      <webElementGuid>756e5114-7f82-4462-b5c0-04cb1c3bdb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;e8ekv6f0 gamut-1lly2r1-VariableProvider-AppWrapper-AppWrapper e1skjn880&quot;]/footer[@class=&quot;gamut-1y7hb43 e1xir4o10&quot;]/div[@class=&quot;gamut-3a1jmv-Box-ContentContainer e1dgn4f70&quot;]/div[@class=&quot;gamut-pnw1bs-LayoutGrid e1f7ortw0&quot;]/div[@class=&quot;gamut-1gkks2k-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-15b6f3e-LayoutGrid e10xj1580&quot;]/div[@class=&quot;gamut-1oivdx9-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-1efsrtw-Box ebnwbv90&quot;]/ul[@class=&quot;gamut-1jk5e01-Box ebdzcwh1&quot;]/li[@class=&quot;gamut-77pqup ebdzcwh0&quot;]/a[@class=&quot;gamut-gi2olp-AnchorBase e14vpv2g0&quot;]</value>
      <webElementGuid>4972292b-09f3-41b0-89ff-d3ec19ea09b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div/div/div[3]/div[2]/ul/li[5]/a</value>
      <webElementGuid>7a180fac-23fd-4280-ac25-d34c979118a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Forums')])[2]</value>
      <webElementGuid>7c0f5849-e105-41fb-a575-8944901b165e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://discuss.codecademy.com/?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.')]</value>
      <webElementGuid>6ddff11f-27aa-4356-9089-11734af3284d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]/a</value>
      <webElementGuid>c056f5d7-5e1c-4468-a844-f93d0dd2dc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://discuss.codecademy.com/?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.' and (text() = 'Forums' or . = 'Forums')]</value>
      <webElementGuid>6053923b-b024-4ac8-ac10-cf461ce7c773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
