<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Full Catalog</name>
   <tag></tag>
   <elementGuidId>3231c197-8cab-4750-ae58-e9434a7b0894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.gamut-1ugzxxi.e1am55210 > a.gamut-gi2olp-AnchorBase.e14vpv2g0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div[2]/div/div/div[3]/div/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc283328-ff4f-4eae-8386-2a3e4da0b9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/catalog/all</value>
      <webElementGuid>622d4013-3e49-405b-b4a4-c607fde4dd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gamut-gi2olp-AnchorBase e14vpv2g0</value>
      <webElementGuid>15d5540c-8f27-4f7e-a15d-12f9f11cfb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full Catalog</value>
      <webElementGuid>6f4ed49e-6e49-4f9b-b0e6-99042c6501bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;e8ekv6f0 gamut-1lly2r1-VariableProvider-AppWrapper-AppWrapper e1skjn880&quot;]/footer[@class=&quot;gamut-1y7hb43 e1xir4o10&quot;]/div[@class=&quot;gamut-3a1jmv-Box-ContentContainer e1dgn4f70&quot;]/div[@class=&quot;gamut-pnw1bs-LayoutGrid e1f7ortw0&quot;]/div[@class=&quot;gamut-1gkks2k-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-2ry0sg e1am55212&quot;]/div[@class=&quot;gamut-glpvwy-LayoutGrid e10xj1580&quot;]/div[@class=&quot;gamut-d1cdmh-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-1efsrtw-Box ebnwbv90&quot;]/ul[@class=&quot;gamut-25mlb6-Box e1am55211&quot;]/li[@class=&quot;gamut-1ugzxxi e1am55210&quot;]/a[@class=&quot;gamut-gi2olp-AnchorBase e14vpv2g0&quot;]</value>
      <webElementGuid>1e3d6463-c2e0-4534-8820-e497ecff0b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div[2]/div/div/div[3]/div/ul/li[6]/a</value>
      <webElementGuid>a2163497-8300-4ee7-918f-b353c099ba7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Full Catalog')]</value>
      <webElementGuid>2f8231b1-5c45-4059-a5df-60e2409bd0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/catalog/all')])[2]</value>
      <webElementGuid>7bf06d5e-c731-4fdd-bb83-3ef42bc325e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/ul/li[6]/a</value>
      <webElementGuid>cd475201-baa0-4d84-89af-57b21c0603c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/catalog/all' and (text() = 'Full Catalog' or . = 'Full Catalog')]</value>
      <webElementGuid>e2e788ea-811a-418d-a32a-ade5cdde2dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
