<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refer a friend</name>
   <tag></tag>
   <elementGuidId>5343e64c-e57f-46bf-9716-723650b688bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.extole-cta-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='extole-7192999675673674589']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d6811cb-2e3a-4033-96b1-a25879178ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a94f7107-fdc1-4198-a824-e5345c050683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>extole-cta-link</value>
      <webElementGuid>edb57fc0-6164-4a16-bcb3-80013ca78ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refer a friend</value>
      <webElementGuid>8c2a437c-66cf-4a47-8447-babd18d49fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extole-7192999675673674589&quot;)/a[@class=&quot;extole-cta-link&quot;]</value>
      <webElementGuid>2f0a6429-5362-4811-8207-05be374d61b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='extole-7192999675673674589']/a</value>
      <webElementGuid>d3744cf7-28d2-4c21-872d-49eab96141b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Refer a friend')]</value>
      <webElementGuid>a8e4b5bf-d571-4889-a23b-f63388fefb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>f3bd1346-326b-48f7-812c-9418d65a6e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
      <webElementGuid>c8a600fd-34e0-4b83-8275-400240cb6bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Refer a friend' or . = 'Refer a friend')]</value>
      <webElementGuid>2302aa9f-00f2-4739-aafe-c4878c2dab39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
