<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Workspaces</name>
   <tag></tag>
   <elementGuidId>dcefd8bc-b112-44fc-8616-c8be302bd27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div/div/div[2]/div/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f43bc742-4c4f-4ca9-b755-9b85668664fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://codecademy.com/pages/workspaces?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.</value>
      <webElementGuid>ede9c099-887e-4c39-aaea-5ac8100194ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gamut-gi2olp-AnchorBase e14vpv2g0</value>
      <webElementGuid>62b7b82b-eca5-4a1a-83d4-23a1d3af765a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workspaces</value>
      <webElementGuid>9eb5ee78-7ff1-4747-b4a6-8c8f2f86d0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;e8ekv6f0 gamut-1lly2r1-VariableProvider-AppWrapper-AppWrapper e1skjn880&quot;]/footer[@class=&quot;gamut-1y7hb43 e1xir4o10&quot;]/div[@class=&quot;gamut-3a1jmv-Box-ContentContainer e1dgn4f70&quot;]/div[@class=&quot;gamut-pnw1bs-LayoutGrid e1f7ortw0&quot;]/div[@class=&quot;gamut-1gkks2k-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-15b6f3e-LayoutGrid e10xj1580&quot;]/div[@class=&quot;gamut-6jvxk2-StyledColumn e1y0e4q30&quot;]/div[@class=&quot;gamut-5kj303-Box ebnwbv90&quot;]/ul[@class=&quot;gamut-1jk5e01-Box ebdzcwh1&quot;]/li[@class=&quot;gamut-77pqup ebdzcwh0&quot;]/a[@class=&quot;gamut-gi2olp-AnchorBase e14vpv2g0&quot;]</value>
      <webElementGuid>2b529531-23a3-427a-99ab-f6d81851b817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div/div/div[2]/div/ul/li[8]/a</value>
      <webElementGuid>4a94527c-bf6a-4a65-bdcd-8b898b3c67e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Workspaces')])[2]</value>
      <webElementGuid>5a8e4f9c-b058-4aec-8f23-e3a97dfc634c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://codecademy.com/pages/workspaces?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.')]</value>
      <webElementGuid>b9e02f83-57ee-4226-a0a5-3b61e262adcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[8]/a</value>
      <webElementGuid>66b6e7da-e0d1-45d5-8c83-7bd9d17f40c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://codecademy.com/pages/workspaces?_gl=1*1l6qpk6*_ga*MzM5NjkyMTY5My4xNjk5OTA4NjU0*_ga_3LRZM6TM9L*MTY5OTkwODY1Ny4xLjAuMTY5OTkwODY2Ni41MS4wLjA.' and (text() = 'Workspaces' or . = 'Workspaces')]</value>
      <webElementGuid>d80bad4d-e8e2-4df7-b0ed-5d92c0eab75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
