<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_art  media  design</name>
   <tag></tag>
   <elementGuidId>3f2f3f9a-5849-4b7e-813c-e36a13d2eb6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.med</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='jjj0']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ecc74b7-d638-447e-93dc-9f2c1f2b69bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/med</value>
      <webElementGuid>ab9d63b9-ba3b-46cd-abf4-2b95d88e995f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>med</value>
      <webElementGuid>291cd520-36c9-40c6-8156-add0d14aafee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cat</name>
      <type>Main</type>
      <value>med</value>
      <webElementGuid>19966152-13e7-4f05-827e-2283ec5aae6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>art / media / design</value>
      <webElementGuid>d250d04e-877a-48df-97a3-696e0c6e416d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jjj0&quot;)/li[4]/a[@class=&quot;med&quot;]</value>
      <webElementGuid>b83d8a50-64cf-4cf1-b930-b2f8fd994475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jjj0']/li[4]/a</value>
      <webElementGuid>96add07d-835f-4f51-9b05-c730b711ad36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/med')]</value>
      <webElementGuid>329a75c7-0552-4647-9fac-b74d5cb7bcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[4]/a</value>
      <webElementGuid>dca057bf-ab78-4524-9a2f-2bc7cd778bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/med' and (text() = 'art / media / design' or . = 'art / media / design')]</value>
      <webElementGuid>677cbb9d-0981-446c-9762-d76974b70203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
