<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_beauty</name>
   <tag></tag>
   <elementGuidId>75b5688a-4cf8-4dd8-8bb4-afb3450d0124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26897f32-d897-4ef3-ad26-df5c5a2221cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/bts</value>
      <webElementGuid>0453fb3d-3993-411e-963b-117476a85e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bts</value>
      <webElementGuid>58ba0f73-5ae5-4fe6-8ba0-b3bcfe852fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cat</name>
      <type>Main</type>
      <value>bts</value>
      <webElementGuid>9ad3f077-0fe7-4cc8-b8fc-15e859f37ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>beauty</value>
      <webElementGuid>4fea5da2-0089-400b-ab10-b09c90b170d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[2]/a[@class=&quot;bts&quot;]</value>
      <webElementGuid>9ca5efe0-20a6-4128-96ed-1dd5ba24b474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[2]/a</value>
      <webElementGuid>e2a01175-7487-4262-8fc7-40c037cafcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/bts')]</value>
      <webElementGuid>df3b7d93-4733-44c3-a692-828aefcc9132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>c116f545-922f-4a49-8ae4-746642609761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/bts' and (text() = 'beauty' or . = 'beauty')]</value>
      <webElementGuid>e1723579-6b00-44e7-8694-680554cb1d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
