<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_craigslist</name>
   <tag></tag>
   <elementGuidId>ae9a57d1-feb0-4e97-9dbc-f10bf2548fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logo > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='logo']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5600b3d-a842-4949-a99a-f4d6a1d8f39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.craigslist.org/about/sites</value>
      <webElementGuid>772a446a-53cf-42b1-9b60-131650e1bdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>craigslist</value>
      <webElementGuid>c521db6d-800f-450f-a121-1398a4d31fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)/a[1]</value>
      <webElementGuid>38831196-5a57-4fd0-9d0d-4d03ae71ee9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='logo']/a</value>
      <webElementGuid>a29773e8-467d-40fb-8414-823ff22f9524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'craigslist')]</value>
      <webElementGuid>2d79ad9b-b5a6-4f55-bf69-2d121d104a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.craigslist.org/about/sites')])[3]</value>
      <webElementGuid>3e6bd15f-b3dd-4d50-aee7-0fc48a44a7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/a</value>
      <webElementGuid>becce42e-6cc2-41a3-bd30-7af0e4592a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.craigslist.org/about/sites' and (text() = 'craigslist' or . = 'craigslist')]</value>
      <webElementGuid>3c568adb-74eb-4d0f-b812-f3d75505b0eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
