<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_event calendar</name>
   <tag></tag>
   <elementGuidId>a05e1a96-9153-455c-b2c5-3fa872d9f16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calban > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='calban']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20360dc7-9fa3-4915-a9d6-50b7504a1277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/eee</value>
      <webElementGuid>0ea42305-cfba-4397-a7e5-87651269f2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>event calendar</value>
      <webElementGuid>ca346102-0d48-4e22-b9f1-5bfe6b022d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calban&quot;)/a[1]</value>
      <webElementGuid>2b4694b7-34b6-4354-a2a6-fd0a33d7e829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='calban']/a</value>
      <webElementGuid>d8b2ba2d-d173-4267-ac5a-a2a106f8e60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'event calendar')]</value>
      <webElementGuid>e1cc5685-ab73-4467-b817-98ff9a3e0b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/eee')]</value>
      <webElementGuid>fd44aa9a-8bca-4cc5-9cdd-445a62ba9a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>72032730-6d41-4448-aeca-e0f0b1f9ae6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/eee' and (text() = 'event calendar' or . = 'event calendar')]</value>
      <webElementGuid>d7f105e2-8afd-41e5-a2ce-65a580b34a6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
