<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_localnews</name>
   <tag></tag>
   <elementGuidId>d232d54e-0f14-4435-bd2a-0ced78d93134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.vnn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc0']/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43992a12-93ce-4269-8b28-242c039d8b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/vnn</value>
      <webElementGuid>f778f20f-138b-4f11-b66b-09a93e27ec5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vnn</value>
      <webElementGuid>3e9e5e82-875a-4495-9c7a-ad5060270040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cat</name>
      <type>Main</type>
      <value>vnn</value>
      <webElementGuid>21356509-ac82-4eec-8368-81afd83613f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>local news</value>
      <webElementGuid>6e3ac515-bcd4-4bb0-b4ba-61a3dddf30d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc0&quot;)/li[8]/a[@class=&quot;vnn&quot;]</value>
      <webElementGuid>cd4741a9-6da1-4047-8373-5b157019aade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc0']/li[8]/a</value>
      <webElementGuid>d717e93a-d14e-4ff7-9f67-5aa555693c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/vnn')]</value>
      <webElementGuid>5dae608f-95d3-4289-9773-29d51c1a8040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>d8adcb1b-6e36-4326-a33b-a9fbbd31030f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/vnn' and (text() = 'local news' or . = 'local news')]</value>
      <webElementGuid>327e7ddd-15e3-431c-adc8-22fe6753b222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
