<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_real estate for sale</name>
   <tag></tag>
   <elementGuidId>d2a96f19-92da-4ce4-b31d-f70883f4b92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='hhh0']/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9ab458e-bc23-4e73-8d31-37ea048d6537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/rea</value>
      <webElementGuid>231ee0b9-e145-4d66-8b42-c7c495fe24d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rea</value>
      <webElementGuid>1dcfd1fa-b4c0-4de5-b748-007c859b1795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cat</name>
      <type>Main</type>
      <value>rea</value>
      <webElementGuid>5ca6b2f9-9cf2-4a28-aad3-901de9adbeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>real estate for sale</value>
      <webElementGuid>8e4f7d9d-60b2-46c7-994d-3e8962dbd4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hhh0&quot;)/li[6]/a[@class=&quot;rea&quot;]</value>
      <webElementGuid>41bdbc3f-3727-47ad-856c-8a46d83f3d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='hhh0']/li[6]/a</value>
      <webElementGuid>c2d48b62-bab7-42f3-8ade-e40e4645c1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/rea')]</value>
      <webElementGuid>e36f03fc-e1da-46f0-9de6-c0d3070a3240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[6]/a</value>
      <webElementGuid>66a99f68-67b3-4e9a-ac03-fffba628683e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/rea' and (text() = 'real estate for sale' or . = 'real estate for sale')]</value>
      <webElementGuid>3640e2d0-734c-4f21-befd-4dee4bfb26de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
