<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_services</name>
   <tag></tag>
   <elementGuidId>973f9508-4def-4d36-91e0-c5a5944989d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bbb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bbb']/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b82e54f1-b04d-462a-94d1-5d5576e8bcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/bbb</value>
      <webElementGuid>48818268-6de8-413a-bc88-86ece976e74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bbb</value>
      <webElementGuid>afa4b403-c766-4a90-8a1d-c2671153c647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alltitle</name>
      <type>Main</type>
      <value>all services</value>
      <webElementGuid>6f14ad04-92bd-4eb9-bd9c-904458c33af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cat</name>
      <type>Main</type>
      <value>bbb</value>
      <webElementGuid>e95e34d7-a3f4-450e-845e-f93412a4e049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>services</value>
      <webElementGuid>7ff0bed5-93c5-4151-a065-b50cdc06a114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb&quot;)/h3[@class=&quot;ban&quot;]/a[@class=&quot;bbb&quot;]</value>
      <webElementGuid>b7260736-acdc-4d03-a985-a779e2942754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bbb']/h3/a</value>
      <webElementGuid>689c9b1e-a5c2-41f7-ae89-4a5ca06c018b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/bbb')]</value>
      <webElementGuid>7e82fc1d-4dd8-4c1a-83ec-728cd5d502c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h3/a</value>
      <webElementGuid>d6183180-246c-4f9d-bfb9-22e90ce508d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/bbb' and (text() = 'services' or . = 'services')]</value>
      <webElementGuid>94efe774-789e-40af-8f67-e6c150fdaa31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
