<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_jobs</name>
   <tag></tag>
   <elementGuidId>066bd439-2a2c-4495-a782-9e2c274f99b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jjj > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jjj']/h3/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>684d34c7-f233-47f2-8a8d-8f7df10cc316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>8f70cdf9-97de-442e-9058-b6ec473bab38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jobs</value>
      <webElementGuid>78cb1fcb-4698-4706-a7be-08d3f1d30235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jjj&quot;)/h3[@class=&quot;ban&quot;]/a[@class=&quot;jjj&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>ab479787-8c74-4aeb-8274-0ccc0931eca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jjj']/h3/a/span</value>
      <webElementGuid>6858b009-4c15-4dde-b39e-d331f47095e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h3/a/span</value>
      <webElementGuid>94e1d174-cfe8-4f0c-9359-79801399f896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'jobs' or . = 'jobs')]</value>
      <webElementGuid>0dfbd64b-8ef1-4210-9cf4-effbeb2c5e6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
