<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_events</name>
   <tag></tag>
   <elementGuidId>5de0f52c-b041-4f4f-b100-a04c0d2f9f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.eve > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc0']/li[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59ce6224-0ba1-43a5-9bc2-bcf4824edd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>c26afd23-5562-48a3-81f4-2dd0783360d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>events</value>
      <webElementGuid>d3def774-cd1f-4031-ab2b-16b7c9b17229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc0&quot;)/li[5]/a[@class=&quot;eve&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>5d1db8ac-59bd-41b5-b0b6-0dd99afb0c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc0']/li[5]/a/span</value>
      <webElementGuid>be3b8a60-c963-4bfd-8e71-4eb5e64d7d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>90b259f0-7191-43d8-8e5d-1e409a7f9832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'events' or . = 'events')]</value>
      <webElementGuid>d93c491c-5ff6-4643-abc9-3a7cfc1f3579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
