<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apts  housing</name>
   <tag></tag>
   <elementGuidId>22b1e17b-635e-456d-b566-481252be71fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.apa > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='hhh0']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd75f766-598f-483d-b694-607522afffe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>356cf45e-2fa0-46d0-87ce-0573828db4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>apts / housing</value>
      <webElementGuid>d15ffe96-5fed-4ba1-acf2-656c0c6479c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hhh0&quot;)/li[1]/a[@class=&quot;apa&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>eb9ccb52-ebee-4937-a7f9-d244dbf40cd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='hhh0']/li/a/span</value>
      <webElementGuid>ada7dadb-15f6-4b30-b8af-8e6055016b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li/a/span</value>
      <webElementGuid>d507aac5-e728-42db-aa25-aab7da022609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'apts / housing' or . = 'apts / housing')]</value>
      <webElementGuid>e4a4e862-f564-4625-ab2c-bde2ef04eaeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
