<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rideshare</name>
   <tag></tag>
   <elementGuidId>3b3b580d-a9b2-4167-894a-8fc808727461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rid > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6f7bd45-e53d-476f-bb85-49a8ba7a3a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>5f10ac62-4aee-4a23-ac6f-d90daa416a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rideshare</value>
      <webElementGuid>1e123adb-451d-4089-bdf6-b2c38a5e0b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[7]/a[@class=&quot;rid&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>e0ee7ab6-430a-4c70-8201-88d19636cee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li[7]/a/span</value>
      <webElementGuid>45a6e88d-fb38-49de-9ccb-65f6f7603457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[7]/a/span</value>
      <webElementGuid>8f40a68f-8880-44b5-b7d7-e71791087e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'rideshare' or . = 'rideshare')]</value>
      <webElementGuid>18ac0e03-4301-446a-a528-a10a2148e713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
