<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_volunteers</name>
   <tag></tag>
   <elementGuidId>307354c4-4560-4de7-b653-c15adb3bb15f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.vol > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li[8]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0717df41-d50f-48e9-8994-6d9ef2872ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>88d26161-ab77-472f-9f0e-946531c036e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>volunteers</value>
      <webElementGuid>eb6aefdd-5c01-4266-bde2-cf8912f720c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[8]/a[@class=&quot;vol&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>79a18096-ce15-4190-85b6-887712f502e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li[8]/a/span</value>
      <webElementGuid>ef965321-dff3-4360-a12e-9f8e6c1c68cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[8]/a/span</value>
      <webElementGuid>10631681-c339-40f3-b142-905cb00820ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'volunteers' or . = 'volunteers')]</value>
      <webElementGuid>618ed1f7-2119-4e61-9f04-b023aaa69cf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
