<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rooms  shared</name>
   <tag></tag>
   <elementGuidId>ba1921bb-4cc5-4eef-81ca-f787041c2dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.roo > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='hhh0']/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>570f50f8-8bc7-4ce2-9db5-81bee35cfd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>403b12f1-73e7-416f-b8f0-2f119b61c7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rooms / shared</value>
      <webElementGuid>51aae00e-94e4-4565-b594-02a703fade60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hhh0&quot;)/li[7]/a[@class=&quot;roo&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>7ee10efb-99a5-4d6a-9985-b4c1d526f830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='hhh0']/li[7]/a/span</value>
      <webElementGuid>ed60cfde-2eff-48fa-8455-91da43d5bfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[7]/a/span</value>
      <webElementGuid>fc189309-8249-4f41-96d1-37214cb6dfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'rooms / shared' or . = 'rooms / shared')]</value>
      <webElementGuid>f4d266b1-e957-4f88-b905-beb6ce89dd94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
