<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_gigs</name>
   <tag></tag>
   <elementGuidId>e42238a6-1e3f-4b02-9880-ea7f920cc12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ggg > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ggg']/h3/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca648edf-af81-47a2-8377-56ad3da8462f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>c0738b68-dcab-4140-bb98-d78961e55df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gigs</value>
      <webElementGuid>96f9a51d-7a93-4b55-8ccc-e22a288b1a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ggg&quot;)/h3[@class=&quot;ban&quot;]/a[@class=&quot;ggg&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>39b3c2b0-f263-4e40-ae74-0bf82a075c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ggg']/h3/a/span</value>
      <webElementGuid>72689347-f731-4cf3-bb43-7f10da5f2176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/h3/a/span</value>
      <webElementGuid>9ea90c44-920f-4025-afa3-d95207a35c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'gigs' or . = 'gigs')]</value>
      <webElementGuid>49e64373-1eb5-4bf1-92d1-4c36b6a9e290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
