<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_computer</name>
   <tag></tag>
   <elementGuidId>f70fcaf7-750b-4f8f-a1f5-ba9595d0e57e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cps > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d31961f-3be1-4ec7-af62-e025526b68c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>59fc01c5-d9be-46f9-94a9-6052539f1723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>computer</value>
      <webElementGuid>8162ee2f-f6a8-439d-9da5-39d8d0e59e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[4]/a[@class=&quot;cps&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>7195841e-eb19-4ff4-9cb3-57aff8c60121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[4]/a/span</value>
      <webElementGuid>dc9fd5ce-f33e-423e-a7f6-765ec49bec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/a/span</value>
      <webElementGuid>2ff1bdd3-7b95-4583-b7a1-bac45bf5b248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'computer' or . = 'computer')]</value>
      <webElementGuid>f2452983-f024-411b-957d-98e345c71a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
