<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_musicians</name>
   <tag></tag>
   <elementGuidId>0d6430f7-685c-4566-93fc-ff5b3fae492a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.muc > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>666eef4b-54c0-4dd1-9583-bc1cb991a433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>0b48c12a-dae6-44a7-a347-f07d64e2d46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>musicians</value>
      <webElementGuid>64b8eb90-b3a9-4980-867f-7e38c4fe158e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[3]/a[@class=&quot;muc&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>c802cb74-eed0-4013-b717-53652e54c6e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li[3]/a/span</value>
      <webElementGuid>54ac1072-0f8c-4dfa-b462-cac753d5e6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a/span</value>
      <webElementGuid>540ac345-6399-4757-9360-7b6c7d8a39c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'musicians' or . = 'musicians')]</value>
      <webElementGuid>1d4f8abc-6c33-4311-aa53-b36d5732c0a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
