<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_household</name>
   <tag></tag>
   <elementGuidId>d9888387-99ff-432e-927d-75197afc752d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hss > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[11]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7aedc311-84a6-400c-bec9-2353a516b578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>efcb9b9c-05ac-49f1-b92f-b1366d1bc3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>household</value>
      <webElementGuid>fa9850a9-6be0-49ab-bc93-8a8831221899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[11]/a[@class=&quot;hss&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>07241bdb-d5b4-4124-94ba-fc0282043b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[11]/a/span</value>
      <webElementGuid>adc1cc3b-033b-4eb4-a3e8-460c5ec7d933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a/span</value>
      <webElementGuid>78ebb58e-eae0-46c5-b7fb-a5f7d9f67862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'household' or . = 'household')]</value>
      <webElementGuid>e140e24b-4382-4c98-816e-6f8a58db9c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
