<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_office  commercial</name>
   <tag></tag>
   <elementGuidId>14f1e587-4047-4772-97da-b75e814e1760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.off > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='hhh0']/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>206a32bd-2dcc-4fba-92a7-2218bc64454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>60a6f542-ac88-4e0d-9f71-872b33c4040e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>office / commercial</value>
      <webElementGuid>6fbf98ae-4ea5-4671-8cf6-308766232d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hhh0&quot;)/li[4]/a[@class=&quot;off&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>f87a7729-52ce-458c-8e9e-bc3159264e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='hhh0']/li[4]/a/span</value>
      <webElementGuid>a6af12dc-b9ca-44b4-9ed5-9180df1e8730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[4]/a/span</value>
      <webElementGuid>5cf8dd94-0989-4afb-86a3-9973c3a460a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'office / commercial' or . = 'office / commercial')]</value>
      <webElementGuid>2c60ebf0-88e7-4c6d-ab9d-3760d782aacd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
