<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_farmgarden</name>
   <tag></tag>
   <elementGuidId>f37f1648-0c6c-46bf-8fcb-d02260212dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fgs > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[8]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7036d8fb-073e-4c6d-84ed-5cc3c5d8ebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>47d1f7b3-6c96-41de-b507-8f19cf5ba6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>farm+garden</value>
      <webElementGuid>2052645b-faa6-40da-836d-5dee2782d571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[8]/a[@class=&quot;fgs&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>74154e7c-36ab-43bf-858a-7d02403ef2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[8]/a/span</value>
      <webElementGuid>2394de9f-4ffa-42c8-b156-1301bb739237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[8]/a/span</value>
      <webElementGuid>2eb21530-c2d4-4347-8221-d9a4bd994507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'farm+garden' or . = 'farm+garden')]</value>
      <webElementGuid>4faf66bc-8d22-4b69-9f1b-8a731b4206e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
