<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_parking  storage</name>
   <tag></tag>
   <elementGuidId>4cc74d7d-7145-4bf8-a81c-1c1489b8f4f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.prk > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='hhh0']/li[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6eb0f3fb-aad2-46b6-95ca-d2e9caa10696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>f243b19b-e4ee-4c55-8fae-28053aaac532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>parking / storage</value>
      <webElementGuid>393cf626-0f0a-4ff1-b6cc-272ffb98538b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hhh0&quot;)/li[5]/a[@class=&quot;prk&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>1e40ec2c-3bef-4159-9987-f574effaad4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='hhh0']/li[5]/a/span</value>
      <webElementGuid>c4b22e34-12e8-4613-a0cc-b3fc575089b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[5]/a/span</value>
      <webElementGuid>07c825d4-c5a5-488f-ba53-40ef17b63db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'parking / storage' or . = 'parking / storage')]</value>
      <webElementGuid>45ae0823-9264-4a80-99a3-9fcb86f23943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
