<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_artists</name>
   <tag></tag>
   <elementGuidId>de178691-b0eb-473b-ae59-d1f12b13e612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ats > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc0']/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13947143-3a19-4789-9170-836cefe7e08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>4da9c68f-785f-4eb9-bce3-171fd6686a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>artists</value>
      <webElementGuid>b066a2aa-6deb-4d57-8c42-6dfbfb0929ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc0&quot;)/li[2]/a[@class=&quot;ats&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>78e8c89d-ee49-4d8f-9206-0bf3bb62cde2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc0']/li[2]/a/span</value>
      <webElementGuid>ee03bfc5-057f-40dc-937b-1e6ab1976e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>5991ee3b-2fac-44d9-a8ce-95df803ab437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'artists' or . = 'artists')]</value>
      <webElementGuid>ed5af76f-9655-42c0-893d-c3fc7181cb3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
