<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_pets</name>
   <tag></tag>
   <elementGuidId>2ac2af8b-613a-4b4d-bc16-b871da5ab851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pet > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>632e3372-361f-4b9a-9be6-131e6daa1c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>b74acd26-cdc9-41f5-9bd4-ceda60d6091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pets</value>
      <webElementGuid>e95da0b2-81e5-4957-bc9a-62884c240438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[4]/a[@class=&quot;pet&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>cb7f6693-841d-4127-9f54-fa32b3c9ab52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li[4]/a/span</value>
      <webElementGuid>f7d0e047-351f-4b6a-8e5a-b50a7bdf24f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[4]/a/span</value>
      <webElementGuid>a9b32a26-0dc0-4dc8-ae2a-d1f390bd2cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'pets' or . = 'pets')]</value>
      <webElementGuid>15b85b83-da1f-4d13-9b77-8205bdeb5687</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
