<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_healthwell</name>
   <tag></tag>
   <elementGuidId>fefa274d-fb7d-4b28-a342-ee147872b802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hws > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[10]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>538da299-c30b-4d64-b8d6-51e268d089ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>435a4f91-2547-4ac5-b5a1-e5ed8b70c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>health/well</value>
      <webElementGuid>928d589a-2c57-498b-a8af-1b27f8fab619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[10]/a[@class=&quot;hws&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>cb001d34-5460-43dc-932f-66240b650701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[10]/a/span</value>
      <webElementGuid>330c5b22-70c1-446c-9076-e6c344959479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a/span</value>
      <webElementGuid>b4f47ee8-dfe2-43f6-a00a-0d8c5c6cd3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'health/well' or . = 'health/well')]</value>
      <webElementGuid>d614a107-aacd-44d7-b4e8-3ef7684fea28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
