<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cellmobile</name>
   <tag></tag>
   <elementGuidId>2b6cabae-3a99-46aa-bc76-176eb9e60ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cms > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15038f73-42e4-445e-88ab-f26800f8341e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>482ca8e8-cc8d-4b81-8f5c-07beeeff96db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cell/mobile</value>
      <webElementGuid>8e589317-7ecf-4d9d-b797-0b4e05076689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[3]/a[@class=&quot;cms&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>29f44ae2-6eb9-415a-b0f1-31e1ba22c205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[3]/a/span</value>
      <webElementGuid>c172bfa8-2f8a-43cc-8483-57cd0f929329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a/span</value>
      <webElementGuid>dddaf63f-93d1-4202-8038-2d726797164f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'cell/mobile' or . = 'cell/mobile')]</value>
      <webElementGuid>42c304d5-43ee-4b34-a812-c9088a10d135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
