<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_activities</name>
   <tag></tag>
   <elementGuidId>4a69f8d9-224f-4b89-832b-58393407657e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.act > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc0']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5bfbc63c-28fa-406f-8b82-3d0807fe6c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>925d2f83-a1d8-4eee-9614-057a53bbefd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>activities</value>
      <webElementGuid>baf1e64a-8fad-4897-8a4a-bdd49427729c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc0&quot;)/li[1]/a[@class=&quot;act&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>f1659ee6-4a8d-4abc-aa69-1b24c329d4af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc0']/li/a/span</value>
      <webElementGuid>706b7950-a120-488d-b1b9-6a26af1c6ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span</value>
      <webElementGuid>635683bc-e5ef-4a0c-ab0e-1063d901b332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'activities' or . = 'activities')]</value>
      <webElementGuid>e4bab580-2b16-49c0-8553-1057ca4dcc87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
