<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_financial</name>
   <tag></tag>
   <elementGuidId>fc5af623-d009-495b-a5b0-0de85be1103a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fns > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[9]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f20692c3-b2ff-411e-a02f-645694e08104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>a547a62c-bcb7-4372-ba0e-3424962213b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>financial</value>
      <webElementGuid>6fc1dcbd-e359-40ed-b05d-0b17e652d056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[9]/a[@class=&quot;fns&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>1d78d33e-8f9e-4d54-b62b-61d6ad8373ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[9]/a/span</value>
      <webElementGuid>3fd9c517-1515-4707-814c-5170968bf612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/span</value>
      <webElementGuid>b7e8de5b-ce6c-48d5-b322-9621c0a86f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'financial' or . = 'financial')]</value>
      <webElementGuid>5e2d1821-42d1-4587-a2cb-7e4af6327789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
