<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cycle</name>
   <tag></tag>
   <elementGuidId>8c64968e-17f9-48d6-8831-a59e517c5ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cys > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[6]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a89dd76c-4ce3-4b3c-81b8-2addb49d3e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>bb897144-e495-4e1f-9702-9bd869c2acdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cycle</value>
      <webElementGuid>b5465d91-6573-44f2-b070-c147a9fa8e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[6]/a[@class=&quot;cys&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>062c5767-c39d-49bc-90b2-55b6fdd89604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[6]/a/span</value>
      <webElementGuid>aec42d9b-ec01-4fdd-be9b-b44ee980fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[6]/a/span</value>
      <webElementGuid>61c492b4-0d25-4e8e-93ea-85f8a5943ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'cycle' or . = 'cycle')]</value>
      <webElementGuid>eedd8ae3-9665-4c59-9b9e-4ccf800b5833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
