<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_education</name>
   <tag></tag>
   <elementGuidId>8c2d3909-0ced-4ad5-9bf9-5294d28d2553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.edu > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='jjj0']/li[8]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18f3377d-d287-4b4a-9329-fe48f1d206c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>11294b42-66c1-4e58-80c2-df41413bcd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>education</value>
      <webElementGuid>4094a2d5-d0cc-48f1-abc9-c31c2ba42ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jjj0&quot;)/li[8]/a[@class=&quot;edu&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>46b3bcc2-9311-485f-8b4a-bc809d9e18c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jjj0']/li[8]/a/span</value>
      <webElementGuid>616e8d29-a2f9-4df7-a09e-c88bd8746102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[8]/a/span</value>
      <webElementGuid>7c65d361-21ed-4e14-b9f8-89ebe351d6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'education' or . = 'education')]</value>
      <webElementGuid>0b5d47ff-14c6-4db4-a23d-dfeb7d1334f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
