<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_housing</name>
   <tag></tag>
   <elementGuidId>35d0294c-3968-472e-b626-91b0eb47f015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hhh > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hhh']/h3/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4cb748e-d7e2-414f-bfd2-ce524c92f87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>7401efea-e1f7-42b2-8619-15eb9b268750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>housing</value>
      <webElementGuid>e9e512b4-92d8-4169-a180-e05be0f7938b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hhh&quot;)/h3[@class=&quot;ban&quot;]/a[@class=&quot;hhh&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>0335fca1-e74f-4d32-8b89-e0c042e165ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hhh']/h3/a/span</value>
      <webElementGuid>5824f937-8d5a-4748-a948-bf92e43a36e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h3/a/span</value>
      <webElementGuid>9fbf133d-c125-4f93-83f4-79ea797384c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'housing' or . = 'housing')]</value>
      <webElementGuid>7d2b4df3-2c0d-49a8-a25d-1e2e02fc05da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
