<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_lostfound</name>
   <tag></tag>
   <elementGuidId>7162d635-e97b-4a96-83a0-08afc5591930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.laf > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a58fa25-6b38-48aa-880d-b80017e8769b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>0c6e9d04-9763-4d4d-a63f-12bdf27c6851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lost+found</value>
      <webElementGuid>97426942-5998-404b-afb0-10fbe82056c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[1]/a[@class=&quot;laf&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>b799a462-bbf2-4803-9f72-670645c0d29d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li/a/span</value>
      <webElementGuid>3261c7b9-386f-4532-b226-7c193c787be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a/span</value>
      <webElementGuid>b7104cd8-d478-4c33-8539-247b5a1b4969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'lost+found' or . = 'lost+found')]</value>
      <webElementGuid>ef7adb64-de7f-4a06-8505-89a3135dd18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
