<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_childcare</name>
   <tag></tag>
   <elementGuidId>63c50ec6-8559-473a-af2a-d65f5c56c343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.kid > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc0']/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94a256b3-684a-47d8-965c-6a892c1d05aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>260520fb-77b3-4742-a728-7f9dbf7e7ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>childcare</value>
      <webElementGuid>c45d6686-ef26-44da-afd2-d62e09ac8471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc0&quot;)/li[3]/a[@class=&quot;kid&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>b883d788-2d6d-43e9-a931-9fc5575fbde6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc0']/li[3]/a/span</value>
      <webElementGuid>48358d6a-3311-44b0-9095-03313f7cbf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>11d8ec9f-7d7e-4b8b-b501-15d0d645e81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'childcare' or . = 'childcare')]</value>
      <webElementGuid>23a05ed9-e54a-40f8-8e0d-acbd06bc51d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
