<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_event</name>
   <tag></tag>
   <elementGuidId>7b3c1997-e622-4ff1-a28b-a9e81fb5d87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.evs > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>427c79fc-44a5-420a-8611-8bab20f9c41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>7f703414-f3b3-4f2c-a789-11ccc06d506e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>event</value>
      <webElementGuid>519a809b-977d-469f-ba42-a8b23ec6dbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[7]/a[@class=&quot;evs&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>a2332340-0424-4312-b07f-f0e921f536f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[7]/a/span</value>
      <webElementGuid>c38b9650-2aa6-4f2f-952d-cc9ad5521792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[7]/a/span</value>
      <webElementGuid>6afbbbb1-bcfe-406f-9cd9-69bb9dc61dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'event' or . = 'event')]</value>
      <webElementGuid>b49b34b1-a293-4e8a-a135-a2a0e78b3aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
