<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_resumes</name>
   <tag></tag>
   <elementGuidId>21eeadac-3d18-47e1-801c-5d01f539fa86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rrr > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rrr']/h3/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>81d35ca2-036a-4912-87af-c155ab794b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>a0879013-4bff-4b35-9cbd-4d93c80e9c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>resumes</value>
      <webElementGuid>1fcb1d53-266b-4eab-a11f-ad33724cb08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rrr&quot;)/h3[@class=&quot;ban&quot;]/a[@class=&quot;rrr&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>996a521f-807c-4667-86be-b7eaf309f4aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rrr']/h3/a/span</value>
      <webElementGuid>bfb51d90-4b3a-4423-b500-b97bb0812c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/h3/a/span</value>
      <webElementGuid>86a2b4cc-f757-4fe2-a962-9e5a3c31f107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'resumes' or . = 'resumes')]</value>
      <webElementGuid>61cd6bff-29b7-4c8d-a093-afec1e779080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
