<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_creative</name>
   <tag></tag>
   <elementGuidId>44492386-1703-46fd-ba87-628d084b7c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.crs > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b452ffe-02dc-4de1-96fc-71a3b7fbdd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>a5f099f5-e796-4584-a379-dd122df18596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>creative</value>
      <webElementGuid>6e0386d1-7dd2-47fb-913d-697acaa82438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[5]/a[@class=&quot;crs&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>1c071905-dba7-449a-9813-21a1f8efff16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li[5]/a/span</value>
      <webElementGuid>1e5a100d-45b1-43d6-9be5-f5c06cd1ee81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[5]/a/span</value>
      <webElementGuid>232ff3b4-de8c-4840-8fb7-c7c17e334c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'creative' or . = 'creative')]</value>
      <webElementGuid>0e4044e2-7a61-4dd9-94a4-a5dce7653205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
