<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_automotive</name>
   <tag></tag>
   <elementGuidId>5f2136e3-65ce-4b31-9a22-21cfdc69ae83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.aos > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='bbb0']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b63aa4e9-13a8-4f43-9e51-378439e0f759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>4ebc9df2-64b7-416b-b701-f9288861609f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>automotive</value>
      <webElementGuid>343634fe-44ac-4f8b-93a9-c920385e2b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bbb0&quot;)/li[1]/a[@class=&quot;aos&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>6c67a806-4aa8-4d17-86e7-8ecd4b5d2229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bbb0']/li/a/span</value>
      <webElementGuid>76883945-6749-44a1-b48d-0b3a595520be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/a/span</value>
      <webElementGuid>5b2947ec-db9f-43c4-a55a-501385c45d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'automotive' or . = 'automotive')]</value>
      <webElementGuid>11aa83f2-d57f-4112-b1c2-922cb82f964d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
