<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_accountingfinance</name>
   <tag></tag>
   <elementGuidId>779bc222-8527-4636-86cb-20ac6496fe58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.acc > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='jjj0']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4fbe1ca7-041b-4a5a-9fcb-954e69c0c262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>7a2040fe-ecae-440b-8971-f907822b087c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>accounting+finance</value>
      <webElementGuid>7b531378-d092-497c-84aa-15c2dd1de43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jjj0&quot;)/li[1]/a[@class=&quot;acc&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>14dc5b44-d4c6-493b-9c11-30e222c150c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='jjj0']/li/a/span</value>
      <webElementGuid>40d2c6dd-6ca6-451e-b57c-ec44402494b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li/a/span</value>
      <webElementGuid>2858b5fb-a0cb-40a2-9b21-17927963b0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'accounting+finance' or . = 'accounting+finance')]</value>
      <webElementGuid>7591377d-40cb-432f-921d-b4b4945722ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
