<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rants  raves</name>
   <tag></tag>
   <elementGuidId>9acc1697-072c-4b79-98a2-aef38c87e4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rnr > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li[6]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f45a7fa-d1e7-4c26-9ce1-32c11972d40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>a6b7e849-fd8c-4405-896a-ba782de83d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rants &amp; raves</value>
      <webElementGuid>db4e4b11-d321-4220-a716-5a8a31112e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[6]/a[@class=&quot;rnr&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>1472fd6e-602c-4604-ad6e-b18c89e78f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li[6]/a/span</value>
      <webElementGuid>b78ab3dd-7de8-4b39-96be-977aa7091320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[6]/a/span</value>
      <webElementGuid>790da26e-a8fb-4709-ada2-ff0c7444bca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'rants &amp; raves' or . = 'rants &amp; raves')]</value>
      <webElementGuid>9dbdefb7-cd5d-4414-bc54-2126188e8ff0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
