<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_community</name>
   <tag></tag>
   <elementGuidId>cf8b8311-3978-492e-aabd-883357d1d78a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ccc']/h3/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c08c98ad-dc89-4328-b3e5-69aa2b94fc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>8a922a56-b200-40f1-8726-46bfe5d32cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>community</value>
      <webElementGuid>ac9d78ff-e395-450f-ba0a-03cf2f7eff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc&quot;)/h3[@class=&quot;ban&quot;]/a[@class=&quot;ccc&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>04b85056-46d3-4cb3-814f-5b16f9b6072e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ccc']/h3/a/span</value>
      <webElementGuid>1780474e-3eb9-4b7f-830c-77717e1d0cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a/span</value>
      <webElementGuid>52502289-5387-4c74-a40f-cc0eaf4532f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'community' or . = 'community')]</value>
      <webElementGuid>a774e364-d8bc-450e-b605-3201f4d67f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
