<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_politics</name>
   <tag></tag>
   <elementGuidId>68816a2e-c0ad-40dd-ab0a-98bbab1f4403</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pol > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc1']/li[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f53bcc10-75f9-4e80-9e5b-9a513b5c549a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>bac4fa33-4bd0-42a5-b6a4-f3510ac12d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>politics</value>
      <webElementGuid>93aa120c-d043-439f-8cc7-332b36f457a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc1&quot;)/li[5]/a[@class=&quot;pol&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>8862c55b-b99b-49c5-a92b-b705da8f02f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc1']/li[5]/a/span</value>
      <webElementGuid>779f68e1-d15d-4e04-849d-c41b268760f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[5]/a/span</value>
      <webElementGuid>8bad8f1d-b606-494e-90c1-6ca8b10c8408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'politics' or . = 'politics')]</value>
      <webElementGuid>f27c2a6e-6a50-45f4-b1f5-72ca326d602b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
