<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_groups</name>
   <tag></tag>
   <elementGuidId>a22c26be-d613-4e5d-ba36-a2562408e4c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.grp > span.txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ccc0']/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a36d8702-a98e-4d90-a599-7b068423aa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>ac607122-f35f-4e0c-a82f-fd0a283e5659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>groups</value>
      <webElementGuid>b05fe65a-7ec5-4a63-879d-68ede8f58ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccc0&quot;)/li[7]/a[@class=&quot;grp&quot;]/span[@class=&quot;txt&quot;]</value>
      <webElementGuid>3706acd9-f1fd-4743-a92b-9426f25f1d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ccc0']/li[7]/a/span</value>
      <webElementGuid>5657ddc4-c716-49fd-89e1-d493555010a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>4fb0e201-ee7a-42e2-bfeb-0b3ade5bb689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'groups' or . = 'groups')]</value>
      <webElementGuid>c4575ced-1004-4e74-aea1-12ab520f4a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
