<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_C</name>
   <tag></tag>
   <elementGuidId>7a8575a3-46c9-4451-bfa0-e4be3c918129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5c24913-3784-458b-a66f-1a8620593ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cs/index.php</value>
      <webElementGuid>458e55ab-d8be-4f77-ac7c-bc0a87de6dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav</value>
      <webElementGuid>fac88f7b-d751-436c-9b5b-cad4165d29ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>C# Tutorial</value>
      <webElementGuid>4c07ab23-41b2-421e-a712-63f08e35baa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C#</value>
      <webElementGuid>8f87e1b5-8286-48ee-8b6b-2285658e964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav&quot;]</value>
      <webElementGuid>331ceef3-ada1-47b9-a464-84a48126bae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a[12]</value>
      <webElementGuid>2f4de059-558a-4789-8739-9c7316a43770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'C#')])[3]</value>
      <webElementGuid>2d8d45b5-3f4a-4c18-bd78-7f1c6daaeac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cs/index.php')])[3]</value>
      <webElementGuid>97936595-4da8-4bfe-bf4f-987068d679d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[12]</value>
      <webElementGuid>40c47d30-b9ee-4ddd-8f16-54462732e763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cs/index.php' and @title = 'C# Tutorial' and (text() = 'C#' or . = 'C#')]</value>
      <webElementGuid>9f176080-8c04-46b6-b48d-775a203644cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a[11]</value>
      <webElementGuid>b7f79650-9824-4299-b4ac-6779ea4c9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'C++')])[3]</value>
      <webElementGuid>1b35e608-de04-47cc-b98d-2ae304c5a472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cpp/default.asp')])[3]</value>
      <webElementGuid>5cfe5c0a-9d78-4d25-b054-3de5ce6bfeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[11]</value>
      <webElementGuid>45494557-aee9-4c94-b5ac-193b88f8a73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cpp/default.asp' and @title = 'C++ Tutorial' and (text() = 'C++' or . = 'C++')]</value>
      <webElementGuid>e6952add-a14f-46a9-aee3-90e2f48326da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
