<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CSS</name>
   <tag></tag>
   <elementGuidId>42a8f603-352f-4138-92ca-40f19f63b80c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3f19bb7-869a-4532-9553-b68a0a585fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/css/default.asp</value>
      <webElementGuid>64a96b60-2126-479b-8704-13d0ea74871c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav</value>
      <webElementGuid>c85a6158-7a10-4b18-a7e6-15806a7bfc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>CSS Tutorial</value>
      <webElementGuid>3f5aeb1c-5191-4825-bfcf-068b78fc56fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSS</value>
      <webElementGuid>3ef4023d-a0ae-444b-8523-301867be271a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav&quot;]</value>
      <webElementGuid>6a32eb5e-d5dc-4ec4-9a92-c3bfe8b6904c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a[2]</value>
      <webElementGuid>2512b0a6-d5c0-4b81-b441-aad72a75f33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CSS')])[3]</value>
      <webElementGuid>285c7b2f-4058-470e-b646-209bea1f80b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/css/default.asp')])[3]</value>
      <webElementGuid>467e7f63-06c6-48c4-8cb7-94edfa69a0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>107895ba-c3db-47f7-9943-358e63bc14df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/css/default.asp' and @title = 'CSS Tutorial' and (text() = 'CSS' or . = 'CSS')]</value>
      <webElementGuid>853c99b3-8c19-4740-9549-de8443fb3dcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
