<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HTML</name>
   <tag></tag>
   <elementGuidId>bb958089-bb18-4735-a1d6-cbf38b39240c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ga-nav.subtopnav_firstitem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6769c84a-1282-434f-b633-59b17304d865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/html/default.asp</value>
      <webElementGuid>619597bb-0eb0-494c-b139-7346e29ae93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav subtopnav_firstitem</value>
      <webElementGuid>e00142dc-72c4-4988-a92a-7282f2f79a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML Tutorial</value>
      <webElementGuid>6bbed2c1-6cfe-44d3-8182-5d60e1f95546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTML</value>
      <webElementGuid>4514ed12-08b9-4d38-bff4-09726aa23481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav subtopnav_firstitem&quot;]</value>
      <webElementGuid>64bebb47-514a-4d61-9164-6a01258ed4d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a</value>
      <webElementGuid>73714bc7-0c87-4f19-aa08-3564801f04e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'HTML')])[3]</value>
      <webElementGuid>7d448959-fe3b-4c87-a273-059ccc213f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/html/default.asp')])[3]</value>
      <webElementGuid>19db1651-94ca-4ee3-a60c-250d570a96fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>fa3850b1-61cc-46dd-8c63-a135bb606b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/html/default.asp' and @title = 'HTML Tutorial' and (text() = 'HTML' or . = 'HTML')]</value>
      <webElementGuid>2f8b0fba-f622-405e-a26e-6e36742da8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
