<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PHP</name>
   <tag></tag>
   <elementGuidId>f0d7c084-bbaa-49d1-985b-9843492cd534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b55fdfb0-61be-4c93-92b2-a9205f87d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/php/default.asp</value>
      <webElementGuid>50774274-84f9-40e3-a2d0-fafc3cc0efc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav</value>
      <webElementGuid>c0996dfe-e808-48ac-a74e-2e58ed6da2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PHP Tutorial</value>
      <webElementGuid>919f2c63-5d55-4fd9-90ec-354fa6f85ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PHP</value>
      <webElementGuid>e0aabab5-3fcc-458a-afb2-72384277a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav&quot;]</value>
      <webElementGuid>80d25c85-34d0-4613-aff4-69b7b1aa9392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a[7]</value>
      <webElementGuid>b8226ac8-118d-45ef-a4a2-e16310cb6382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'PHP')])[3]</value>
      <webElementGuid>900bcecf-3d4a-44d9-86f6-9e58c1294f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/php/default.asp')])[3]</value>
      <webElementGuid>84025679-fa92-415f-99f6-46e4ed6aba97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[7]</value>
      <webElementGuid>d6ca1b67-9f9d-49af-8e56-ff836f666ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/php/default.asp' and @title = 'PHP Tutorial' and (text() = 'PHP' or . = 'PHP')]</value>
      <webElementGuid>ddcf2d7f-83e3-4e9a-9331-22ec7ca69358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
