<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-logo ws-hover-text-green</name>
   <tag></tag>
   <elementGuidId>64f5f28f-51ed-40a8-92bc-5893d0b647a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='w3-logo']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-logo.ws-hover-text-green</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d647216d-9820-4bb6-bcda-7af570f9bc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-logo ws-hover-text-green</value>
      <webElementGuid>cb345636-8121-4bd9-a970-7ed38306c948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0524ca9-8b35-41f4-8c6c-9d6788cf9535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w3-logo&quot;)/i[@class=&quot;fa fa-logo ws-hover-text-green&quot;]</value>
      <webElementGuid>5f9cbfbb-955d-4a36-b338-6a9a1ef2e5a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='w3-logo']/i</value>
      <webElementGuid>e6d034e6-0ae9-4dab-b689-392752b57cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>9dd1fad6-35a7-42a0-98de-0515ae4a2b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
