<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-logo ws-hover-text-green</name>
   <tag></tag>
   <elementGuidId>d6ba5b58-0325-47ba-b3af-e7710fa8e29e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='w3-logo']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-logo.ws-hover-text-green</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bdc0e8b1-5c7e-4a83-9b07-aa17368ec7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-logo ws-hover-text-green</value>
      <webElementGuid>412c1094-907b-4246-badd-dbebb4cf2c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d771bb58-95d4-4a3a-a1b3-d6022a06f5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w3-logo&quot;)/i[@class=&quot;fa fa-logo ws-hover-text-green&quot;]</value>
      <webElementGuid>3bf32b74-f0f6-4450-9048-bc276cf1488f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='w3-logo']/i</value>
      <webElementGuid>d64ef789-bacd-4682-8575-b459a36c06b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>eefbc541-c28f-44c6-a3d4-92cdf0be0cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
