<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-logo ws-hover-text-green</name>
   <tag></tag>
   <elementGuidId>f4e1410b-23db-4491-a0c0-3bda9b2d90e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='w3-logo']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-logo.ws-hover-text-green</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9d03734e-dd6d-436b-a3e9-5654a49a660e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-logo ws-hover-text-green</value>
      <webElementGuid>bcd53a1f-ef8c-4c84-af1f-af33fdcdcdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de3eac2f-edc2-4f19-89c8-02c782d83dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w3-logo&quot;)/i[@class=&quot;fa fa-logo ws-hover-text-green&quot;]</value>
      <webElementGuid>23f0bd2c-40da-45d5-bef5-4342f5d43bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='w3-logo']/i</value>
      <webElementGuid>c411c9b7-daa9-4e96-a36f-2c79e8a4626d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>8ae1190a-5d13-4d60-b0c8-c40f065819d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
